FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/database.py ./database.py
COPY backend/config.py ./config.py

COPY backend/models.py .
COPY alembic.ini .
COPY alembic ./alembic


CMD ["sh", "-c", "sleep 5 && alembic upgrade head"]