"""Change column in template table

Revision ID: 7b41d87b17d7
Revises: 9f540b56d86a
Create Date: 2025-05-09 19:24:16.193357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b41d87b17d7'
down_revision: Union[str, None] = '9f540b56d86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('templates', sa.Column('preview_image', sa.String(length=255), nullable=True))
    op.add_column('templates', sa.Column('document_path', sa.String(length=255), nullable=True))
    op.add_column('templates', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.drop_column('templates', 'name')
    op.drop_column('templates', 'file_path')
    op.drop_column('templates', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('templates', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('templates', 'last_modified')
    op.drop_column('templates', 'document_path')
    op.drop_column('templates', 'preview_image')
    op.drop_column('templates', 'title')
    # ### end Alembic commands ###
