"""delete column organization_id in emplyees

Revision ID: b28cc56a4ffd
Revises: c486a97f0522
Create Date: 2025-05-26 01:32:46.145091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28cc56a4ffd'
down_revision: Union[str, None] = 'c486a97f0522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_organization_id_fkey', 'employees', type_='foreignkey')
    op.drop_column('employees', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_organization_id_fkey', 'employees', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
