"""delete columns from letter history

Revision ID: c486a97f0522
Revises: 095f88671862
Create Date: 2025-05-23 04:16:29.885215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c486a97f0522'
down_revision: Union[str, None] = '095f88671862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('letter_history_signer_id_fkey', 'letter_history', type_='foreignkey')
    op.drop_constraint('letter_history_adressee_id_fkey', 'letter_history', type_='foreignkey')
    op.drop_column('letter_history', 'signer_id')
    op.drop_column('letter_history', 'adressee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_history', sa.Column('adressee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('letter_history', sa.Column('signer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('letter_history_adressee_id_fkey', 'letter_history', 'adressee', ['adressee_id'], ['id'])
    op.create_foreign_key('letter_history_signer_id_fkey', 'letter_history', 'signers', ['signer_id'], ['id'])
    # ### end Alembic commands ###
