"""Add cascade delete

Revision ID: db7855db1df4
Revises: 7b41d87b17d7
Create Date: 2025-05-09 20:44:00.405514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7855db1df4'
down_revision: Union[str, None] = '7b41d87b17d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('letter_history_user_id_fkey', 'letter_history', type_='foreignkey')
    op.create_foreign_key(None, 'letter_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('templates_author_id_fkey', 'templates', type_='foreignkey')
    op.create_foreign_key(None, 'templates', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.create_foreign_key('templates_author_id_fkey', 'templates', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'letter_history', type_='foreignkey')
    op.create_foreign_key('letter_history_user_id_fkey', 'letter_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
